# Generated by Django 4.1.3 on 2023-01-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profilepics/images/profile.2.png', null=True, upload_to=''),
        ),
    ]
